<?php
/*
* $Id: xoops_version.php,v 1.1 2006/03/27 01:06:49 mikhail Exp $
* Module: WF-Snippets
* Version: v1.00
* Release Date: 15 July 2005
* Author: hsalazar, after Catzwolf
* Licence: GNU
*/

$modversion['name'] = _MI_SNIPM_NAME;
$modversion['version'] = 1.0;
$modversion['description'] = _MI_SNIPMD_DESC;
$modversion['author'] = 'Catzwolf, Hsalazar';
$modversion['credits'] = 'Many thanks to Hsalazar, he is the man behind this one.';
//$modversion['help'] = "snippets.html";
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/snippets_slogo.png';
$modversion['dirname'] = 'wfsnippets';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/category.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/snippets.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'snipcats';
$modversion['tables'][1] = 'snippets';
$modversion['tables'][2] = 'snippets_votedata';
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'snippets_search';

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = _MI_SNIPSUB_SMNAME1;//
//$modversion['sub'][1]['url'] = "submit.php?op=add";//

// Templates
$modversion['templates'][1]['file'] = 'snippets_category.html';
$modversion['templates'][1]['description'] = 'Display category';
$modversion['templates'][2]['file'] = 'snippets_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'snippets_body.html';
$modversion['templates'][3]['description'] = 'Display snippet';
$modversion['templates'][4]['file'] = 'snippets_ratefile.html';
$modversion['templates'][4]['description'] = '';
// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'index.php';
$modversion['comments']['itemName'] = 't';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfsnippets_com_approve';
$modversion['comments']['callback']['update'] = 'wfsnippets_com_update';
